In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
# sentences

sent = [
    "The quick brown fox jumps over the lazy dog",
    "I love programming in Python",
    "The sky is blue and beautiful",
    "I like to eat pizza",
    "I love to play cricket",
    "I love to watch movies",
]

In [4]:
sent

['The quick brown fox jumps over the lazy dog',
 'I love programming in Python',
 'The sky is blue and beautiful',
 'I like to eat pizza',
 'I love to play cricket',
 'I love to watch movies']

In [5]:
# define the vocabulary size
vocab_size = 10000

# one hot encode the sentences
encoded_sent = [one_hot(sent, vocab_size) for sent in sent]
encoded_sent



[[3045, 9602, 9017, 6109, 7768, 3588, 3045, 3077, 5681],
 [7590, 6104, 797, 188, 9472],
 [3045, 5207, 2668, 2151, 3068, 1762],
 [7590, 4582, 1326, 7562, 8146],
 [7590, 6104, 1326, 9441, 7942],
 [7590, 6104, 1326, 464, 7367]]

In [ ]:
# word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [7]:
import numpy as np


sent_length = 8

embedded_docs = pad_sequences(encoded_sent, padding='pre', maxlen=sent_length)



In [8]:
embedded_docs

array([[9602, 9017, 6109, 7768, 3588, 3045, 3077, 5681],
       [   0,    0,    0, 7590, 6104,  797,  188, 9472],
       [   0,    0, 3045, 5207, 2668, 2151, 3068, 1762],
       [   0,    0,    0, 7590, 4582, 1326, 7562, 8146],
       [   0,    0,    0, 7590, 6104, 1326, 9441, 7942],
       [   0,    0,    0, 7590, 6104, 1326,  464, 7367]])

In [9]:
# feature representation

dim = 10

model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 205ms/step


array([[[-0.00648808, -0.00026999, -0.04495842, -0.0158859 ,
         -0.0306559 , -0.02654059,  0.01415036,  0.01086124,
          0.04794474,  0.04896263],
        [-0.04660771, -0.02723545, -0.01917157,  0.00551919,
          0.03000471, -0.01924753, -0.0169548 ,  0.02843908,
         -0.03504316, -0.03797138],
        [ 0.02896309, -0.0459617 , -0.00786892, -0.0441445 ,
         -0.00034753,  0.04569883,  0.03683691, -0.01544933,
          0.03043901, -0.00319499],
        [-0.00938727,  0.02097413,  0.01156095,  0.02425441,
          0.0387901 , -0.02916194, -0.03960799, -0.01911153,
         -0.04308397, -0.03483138],
        [ 0.00448511,  0.03888622, -0.04374703,  0.0134634 ,
         -0.04555441, -0.0051366 ,  0.0008806 , -0.00402126,
          0.01397843, -0.00794388],
        [ 0.01943568,  0.02787531, -0.01428277, -0.04515622,
         -0.00155758,  0.04483234, -0.04090435,  0.02878458,
         -0.00690553,  0.00781257],
        [-0.03373565, -0.04834968,  0.00418177,  0.0

In [11]:
embedded_docs[0]

array([9602, 9017, 6109, 7768, 3588, 3045, 3077, 5681])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[-0.00648808, -0.00026999, -0.04495842, -0.0158859 , -0.0306559 ,
        -0.02654059,  0.01415036,  0.01086124,  0.04794474,  0.04896263],
       [-0.04660771, -0.02723545, -0.01917157,  0.00551919,  0.03000471,
        -0.01924753, -0.0169548 ,  0.02843908, -0.03504316, -0.03797138],
       [ 0.02896309, -0.0459617 , -0.00786892, -0.0441445 , -0.00034753,
         0.04569883,  0.03683691, -0.01544933,  0.03043901, -0.00319499],
       [-0.00938727,  0.02097413,  0.01156095,  0.02425441,  0.0387901 ,
        -0.02916194, -0.03960799, -0.01911153, -0.04308397, -0.03483138],
       [ 0.00448511,  0.03888622, -0.04374703,  0.0134634 , -0.04555441,
        -0.0051366 ,  0.0008806 , -0.00402126,  0.01397843, -0.00794388],
       [ 0.01943568,  0.02787531, -0.01428277, -0.04515622, -0.00155758,
         0.04483234, -0.04090435,  0.02878458, -0.00690553,  0.00781257],
       [-0.03373565, -0.04834968,  0.00418177,  0.01857713, -0.04710882,
        -0.02111555, -0.04502639, -0.01622126